on: [push]

jobs:
  clone_job:
   runs-on: ubuntu-latest
   name: Clone
   steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
  scanmycode_job:
    runs-on: ubuntu-latest
    name: Scan using Betterscan
    steps:
      - name: Betterscan action step
        id: scan
        uses: topcodersonline/betterscan@v3
